# Generated by Django 4.0.2 on 2022-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0002_dest_actual_price_dest_disscunt_dest_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='main_cat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dest',
            name='sub_cat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
