# Generated by Django 4.0.2 on 2022-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0005_rename_dest_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='pro_cat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
