# Generated by Django 4.0.2 on 2022-04-14 08:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0006_product_table_pro_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
