# Generated by Django 4.0.2 on 2022-04-22 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('womenwear', '0007_product_table_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('loality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zippcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman and Nicobar', 'Andaman and Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat ', 'Gujarat '), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Karnataka', 'Karnataka'), ('Kerala ', 'Kerala '), ('Lakshadweep', 'Lakshadweep'), ('Ladakh', 'Ladakh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur ', 'Manipur '), ('Meghalaya ', 'Meghalaya '), ('Mizoram ', 'Mizoram '), ('Nagaland ', 'Nagaland '), ('Odisha ', 'Odisha'), ('Punjab', 'Punjab '), ('Puducherry', 'Puducherry'), ('Rajasthan ', 'Rajasthan'), ('Sikkim ', 'Sikkim '), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana ', 'Telangana '), ('Tripura ', 'Tripura '), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand ', 'Uttarakhand '), ('West Bengal', 'West Bengal')], max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='womenwear.customer')),
                ('product_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='womenwear.product_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='womenwear.product_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
