# Generated by Django 4.0.2 on 2022-04-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0008_customer_orderplaced_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='loality',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zippcode',
            new_name='zipcode',
        ),
    ]
