# Generated by Django 4.0.2 on 2022-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0009_rename_loality_customer_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='bottom_Fabric',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='closure_Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='colours',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product_table',
            name='detailings',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='garment_Length',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='hemline',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='img2',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='img3',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='img4',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='img5',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='img6',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='img7',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='neckline',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='number_of_pieces',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='occasion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='print',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='sleeves_Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='top_Fabric',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='transparency',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='product_table',
            name='washing_Instructions',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product_table',
            name='weave',
            field=models.CharField(default='', max_length=50),
        ),
    ]
