# Generated by Django 4.0.2 on 2022-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0010_product_table_bottom_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Mobile_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_table',
            name='washing_Instructions',
            field=models.CharField(default='', max_length=100),
        ),
    ]
