# Generated by Django 4.0.2 on 2022-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0011_customer_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='detailings',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='washing_Instructions',
            field=models.CharField(default='', max_length=200),
        ),
    ]
