# Generated by Django 4.0.2 on 2022-05-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0012_alter_product_table_detailings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='img8',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
