# Generated by Django 4.0.2 on 2022-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0014_alter_product_table_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
