# Generated by Django 4.0.2 on 2022-05-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0015_alter_product_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='colours',
            field=models.CharField(default='', max_length=100),
        ),
    ]
