# Generated by Django 4.0.2 on 2022-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0016_alter_product_table_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
