# Generated by Django 4.0.2 on 2022-05-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0017_orderplaced_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='commonfieldform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('phone_no', models.CharField(max_length=14)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='Mobile_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('commonfieldform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='womenwear.commonfieldform')),
                ('topic', models.CharField(max_length=200)),
                ('orderid', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            bases=('womenwear.commonfieldform',),
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('commonfieldform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='womenwear.commonfieldform')),
                ('whatsapp', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=70)),
                ('enquiry', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            bases=('womenwear.commonfieldform',),
        ),
    ]
