# Generated by Django 4.0.2 on 2022-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0018_commonfieldform_alter_customer_mobile_no_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
