# Generated by Django 4.0.2 on 2022-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0019_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
