# Generated by Django 4.0.2 on 2022-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0023_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
