# Generated by Django 4.0.2 on 2022-06-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0026_rename_amount_orderplaced_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payment_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payment_mode',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='tracking_no',
            new_name='razorpay_signature',
        ),
    ]
