# Generated by Django 4.0.2 on 2022-06-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0028_alter_product_table_img8'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='actual_price_usa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_table',
            name='sell_price_usa',
            field=models.IntegerField(null=True),
        ),
    ]
