# Generated by Django 4.0.2 on 2022-06-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0029_product_table_actual_price_usa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_table',
            name='actual_price_usa',
        ),
        migrations.RemoveField(
            model_name='product_table',
            name='sell_price_usa',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Australia', 'Australia'), ('Singapore', 'Singapore')], max_length=60, null=True),
        ),
    ]
