# Generated by Django 4.0.2 on 2022-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenwear', '0030_remove_product_table_actual_price_usa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Australia', 'Australia'), ('Singapore', 'Singapore')], max_length=60),
        ),
    ]
