from imaplib import _Authenticator
import profile
from re import template
from tokenize import Name
from xml.etree.ElementInclude import include
from django.core.mail import EmailMessage
from django.urls import path 
from django.contrib.auth import views as auth_views
from womenwear.forms import LoginForm
from womenwearusa import views
from womenwear.forms import LoginForm,MyPasswordChangeForm, MypasswordResetForm,MySetPasswordForm

urlpatterns = [
    path('', views.home, name='home'),
    path('womens_kurta/', views.womens_kurta, name='kurta'),
    path('women/', views.women, name='women'),
    path('womenPalazzo&pants/', views.WomenPalazzo_pants, name='womenPalazzo&pants'),
    path('womenLehenga/', views.WomenLehenga, name='womenLehenga'),
    path('womenSkirts/', views.WomenSkirts, name='womenSkirts'),
    path('womenNight_Wear/', views.WomenNight_Wear, name='womenNight_Wear'),
    path('womenCasual_Wear/', views.WomenCasual_Wear, name='womenCasual_Wear'),
    path('womenParty_Wear/', views.WomenParty_Wear, name='womenParty_Wear'),
    path('womenBlouse/', views.WomenBlouse, name='womenBlouse'),
    path('husband/', views.husband, name='husband'),
    path('husbandShirts/', views.HusbandShirts, name='husbandShirts'),
    path('husbandEmbroideredkurta/', views.HusbandEmbroideredkurta, name='husbandEmbroideredkurta'),
    path('husbandWaistcoat/', views.HusbandWaistcoat, name='husbandWaistcoat'),
    path('husbandKurta/', views.HusbandKurta, name='husbandKurta'),
    path('husbandShortkurta/', views.HusbandShortkurta, name='husbandShortkurta'),
    path('husbandKurtapajamaset/', views.HusbandKurtapajamaset, name='husbandKurtapajamaset'),
    path('husbandSherwani/', views.HusbandSherwani, name='husbandSherwani'),
    path('husbandNightWear/', views.HusbandNightWear, name='husbandNightWear'),
    path('accessories/', views.accessories, name='accessories'),
    path('international/', views.international, name='itorder'),
    path('Kids_Wear/', views.Kids_Wear, name='Kids_Wear'),
    path('kidsgirlsFrocks/', views.KidsgirlsFrocks, name='kidsgirlsFrocks'),
    path('kidsgirlsKurtasets/', views.KidsgirlsKurtasets, name='kidsgirlsKurtasets'),
    path('kidsgirlsLehengasets/', views.kidsgirlsLehengasets, name='kidsgirlsLehengasets'),
    path('kidsgirlsTops_Tunics/', views.kidsgirlsTops_Tunics, name='kidsgirlsTops_Tunics'),
    path('kidsgirlsNight_Wear/', views.kidsgirlsNight_Wear, name='kidsgirlsNight_Wear'),
    path('kidsboysKurta/', views.kidsboysKurta, name='kidsboysKurta'),
    path('kidsboysKurtasets/', views.kidsboysKurtasets, name='kidsboysKurtasets'),
    path('kidsboysPartyWear/', views.kidsboysPartyWear, name='kidsboysPartyWear'),
    path('kidsboysShirt/', views.kidsboysShirt, name='kidsboysShirt'),
    path('kidsboysNightWear/', views.kidsboysNightWear, name='kidsboysNightWear'),
    path('jewellery/', views.jewellery, name='jewellery'),
    path('Fashion_jewellery/', views.Fashion_jewellery, name='Fashion_jewellery'),
    path('Earrings/', views.Earrings, name='Earrings'),
    path('Flower_jewellery/', views.Flower_jewellery, name='Flower_jewellery'),
    path('Silver_jewellery/', views.Silver_jewellery, name='Silver_jewellery'),
    path('Necklace_Pendant/', views.Necklace_Pendant, name='Necklace_Pendant'),
    path('Bracelets_Bangle/', views.Bracelets_Bangle, name='Bracelets_Bangle'),
    path('Rings/',views.Ringsjewellery, name='Rings'),
    path('Hair_Accessories/',views.Hair_Accessories, name='Hair_Accessories'),
    path('Scarf/',views.Scarf, name='Scarf'),
    path('Menjewellery/',views.Menjewellery, name='Menjewellery'),
    path('Kids_jewellery/',views.Kids_jewellery, name='Kids_jewellery'),
    path('Suit_Kurta/', views.womens_suit, name='suit'),
    path('waistband/', views.waistband, name='waistband'),
    path('Potli/', views.Potli, name='Potli'),
    path('Personal_care/', views.Personal_care, name='Personal_care'),
    path('Wedding_Collection/', views.Wedding_Collection, name='Wedding_Collection'),
    path('Groom/', views.Groom, name='Groom'),
    path('womens_top/', views.womens_top, name='top'),
    path('womens_goun/', views.womens_goun, name='goun'),
    path('Bride/', views.Bride, name='Bride'),
    path('Groom_Bride_Family/', views.Groom_Bride_Family, name='Groom_Bride_Family'),
    path('Bridesmaids/', views.Bridesmaids, name='Bridesmaids'),
    path('Designer_Collection/', views.Designer_Collection, name='Designer_Collection'),
    path('Under_799/', views.Under_799, name='Under_799'),
    path('Under_899/', views.Under_899, name='Under_899'),
    path('Under_999/', views.Under_999, name='Under_999'),
    path('womens_indo/', views.womens_indo, name='indo'),
    path('product/<slug>', views.product, name='details'),
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.Contact, name='contact'),
    path('wishlist/', views.Wishlist, name='wishlist'),
    path('listview/', views.list, name='list'),
    path('remove_list/', views.remove_list, name='remove_list'),
    path('policy/', views.policy, name='policy'),
    path('support/', views.support, name='support'),
    path('Wholesale/', views.Wholesale, name='Wholesale'),
    path('terms/', views.terms, name='terms'),
    path('size/', views.size, name='size'),
    path('shipping/', views.shipping, name='shipping'),
    path('exchange/', views.exchange, name='exchange'),
    path('payment/', views.payment, name='payment'),
    path('search/', views.search, name='search'),
    path('signup/', views.CustomerRegistrationView.as_view(), name='login'),
    path('add-to-cart/', views.cart, name='add-to-cart'),
    path('add-to-wishlist/', views.removelist, name='add-to-wishlist'),
    path('checkout/', views.checkout, name='checkout'),
    path('order/', views.order, name='order'),
    path('paymentdone/', views.payment_done, name='paymentdone'),
    path('cart/', views.show_cart, name='showcart'),
    path('pluscart/', views.plus_cart),
    path('minuscart/', views.minus_cart),
    path('removecart/', views.remove_cart),
    path('removewishlist/', views.remove_wishlist),
    path('signin/', auth_views.LoginView.as_view(next_page='profile' ,template_name='../templates/usa/signin.html', authentication_form=LoginForm) ,name="signin"),
    path('logout/',auth_views.LogoutView.as_view(next_page='signin'),name='logout'),
    path('profile/', views.ProfileView.as_view() , name='profile'),
    path('changepassword/', auth_views.PasswordChangeView.as_view(template_name='../templates/usa/changepassword.html',form_class=MyPasswordChangeForm,success_url='/passwordchangedone/') ,name="changepassword"),
    path('passwordchangedone/',auth_views.PasswordChangeDoneView.as_view(template_name='../templates/usa/passwordchangedone.html'),name='passwordchangedone'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='../templates/usa/password_reset.html',form_class=MypasswordResetForm),name='password_reset'),
    path('password-reset-done/',auth_views.PasswordResetDoneView.as_view(template_name='../templates/usa/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='../templates/usa/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='../templates/usa/password_reset_complete.html'),name='password_reset_complete'),
    path('address/',views.address,name='address'),
    path('invoice/',views.invoice,name='invoiceind'),

]

